name: Build Mac Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyqt5 matplotlib numpy scipy pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed convecho.py
      env:
        PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: macos-executable
        path: dist/convecho
